# Generated by Django 4.1.5 on 2024-05-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoAppSrc', '0002_alter_todoitems_todofile_alter_todoitems_todoimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='todoFile',
        ),
    ]
